---
title: "Umfrageergebnisse zum Nachhaltigen Wohnen"
format:
  dashboard:
#  html: 
#    toc: false
    theme: 
      - cosmo
      - custom.scss
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(crosstalk)
library(tidyverse)
library(DT)
library(plotly)
library(RColorBrewer)

# load data ----
data <- read.csv("data.csv") %>% 
  mutate(ID = row_number()) %>% 
  select(-Zeitstempel)
  
# create shared data for crosstalk
shared_data <- SharedData$new(data, key = ~ID)
```

## Row {height=15% expandable: false}


```{r, echo=FALSE, message=FALSE, warning=FALSE}
#| expandable: false

cat("Hier kommen Filter hin")
```

## Row {height=85%}

### Column {.tabset width=70%}

::: {.card title="Themen"}
An was denken Sie, wenn Sie den Begriff Nachhaltigkeit hören?
```{r, echo=FALSE, message=FALSE, warning=FALSE}
tibble(response = data$An.was.denken.Sie..wenn.Sie.den.Begriff.Nachhaltigkeit.hören..) %>%
  mutate(themes = str_split(response, ";")) %>% 
  unnest(themes) %>% 
  count(themes, name = "Frequency") %>%
  mutate(themes = factor(themes, levels = themes[order(-Frequency)])) %>%  # Reorder factor levels
  plot_ly(x = ~themes, y = ~Frequency, type = 'bar', name = 'Sustainability Themes',
          marker = list(color = ~-Frequency, 
                        colorscale = 'Greens')) %>%
  layout(title = '',
         xaxis = list(title = '', 
                      tickangle = -45),
         yaxis = list(title = 'Antworthäufigkeit'))
```
:::

::: {.card title="Wohnraum"}
Ist es für Sie wichtig Ihren Wohnraum und Ihre Einrichtung nachhaltig zu gestalten?
```{r, echo=FALSE, message=FALSE, warning=FALSE}
tibble(rating = data$Ist.es.für.Sie.wichtig.Ihren.Wohnraum.und.ihre.Einrichtung.nachhaltig.zu.gestalten.) %>%
  count(rating, name = "Frequency") %>%
#  mutate(rating = factor(rating, levels = rating[order(-Frequency)])) %>%
plot_ly(x = ~rating, y = ~Frequency, type = 'bar', name = 'Importance Ratings',
          marker = list(color = ~-Frequency, 
                        colorscale = 'Greens')) %>%
  layout(title = '',
         xaxis = list(title = '',
                      tickvals = ~rating,
                      ticktext = c('1 \n Äußerst wichtig', '2', '3', '4 \n Überhaupt nicht wichtig'),
                      tickangle = -45),
         yaxis = list(title = 'Antworthäufigkeit'))

```
:::


::: {.card title="Upcycling"}
Ist Ihnen der Begriff Upcycling im Bereich Wohnen bekannt?
```{r, echo=FALSE, message=FALSE, warning=FALSE}
tibble(response = data$Ist.Ihnen.der.Begriff.Upcycling.im.Bereich.Wohnen.bekannt.) %>%
  mutate(response = recode(response, "Der Begriff ist mir bekannt, aber in anderen Lebensbereichen." = "Der Begriff ist mir bekannt, \naber in anderen Lebensbereichen.")) %>% 
  count(response, name = "Frequency") %>%
  mutate(response = factor(response, levels = response[order(-Frequency)])) %>%
  plot_ly(x = ~response, y = ~Frequency, type = 'bar', name = 'Upcycling Awareness',
          marker = list(color = ~-Frequency, 
                        colorscale = 'Viridis')) %>%
  layout(title = '',
         xaxis = list(title = '',
                      tickangle = -45),
         yaxis = list(title = 'Antworthäufigkeit'))

```
:::

### Column {width=30%}
```{r, echo=FALSE, message=FALSE, warning=FALSE}

cat("???")
```

